ericdesj/KRUSH

.idea/markdown-navigator.xml, .idea/misc.xml, .idea/vcs.xml, README.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/cs/dal/krush/MainActivity.java, app/src/main/java/cs/dal/krush/TutorCalendarActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_tutor_calendar.xml, app/src/main/res/values-w820dp/dimens.xml, app/src/main/res/values/dimens.xml
Implemented a simple Material Calendar view for issue #4 .
- See calendar [see GitHub repo](https://github.com/prolificinteractive/material-calendarview)
- Also set the main view of the application to a generic empty activity
=> Tutor calendar

app/src/main/java/cs/dal/krush/StudentHomeActivity.java, app/src/main/java/cs/dal/krush/TutorHomeActivity.java, app/src/main/res/layout/activity_student_home.xml, app/src/main/res/layout/activity_tutor_home.xml
Has tutor and student home views. Empty activities and classes setup
=> Tutor home view

app/build.gradle, app/src/main/java/cs/dal/krush/MainActivity.java, app/src/main/java/cs/dal/krush/StudentMainActivity.java, app/src/main/java/cs/dal/krush/StudentProfileFragment.java, app/src/main/java/cs/dal/krush/StudentQuickBookFragment.java, app/src/main/java/cs/dal/krush/StudentSessionsFragment.java, app/src/main/java/cs/dal/krush/TutorMainActivity.java, app/src/main/java/cs/dal/krush/TutorSessionsFragment.java, app/src/main/java/cs/dal/krush/helpers/BottomNavigationViewHelper.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/student_home.xml, app/src/main/res/layout/student_profile.xml, app/src/main/res/layout/student_quickbook.xml, app/src/main/res/layout/student_sessions.xml, app/src/main/res/layout/tutor_sessions.xml, app/src/main/res/menu/student_bottom_nav_items.xml
Created the following fragment views with navigation:
Student:
- quickbook
- profile
- sessions history
Tutor:
- sessions history
Refactored login buttons to say "student login" and "tutor login"
=> Setup fragment views

.idea/misc.xml, app/src/main/res/layout/activity_main.xml
While working on the project update, I noticed two things I wanted to change on the MainActivity screen:
- Make the 'KRUSH' text larger
- Changed the button font colour
Bonus:
- Changed the slogan
=> Updated the styles on the MainActivity

app/src/main/res/layout/tutor_calendar_fragment.xml
Changed the colour to the app's primary.
=> Changed the on-select colour to primary for the calendar

app/src/main/res/values/styles.xml
Successfully removed unwanted header
=> Removed app header from main page

app/src/main/java/cs/dal/krush/SessionItemFragment.java, app/src/main/java/cs/dal/krush/StudentQuickBookItemFragment.java, app/src/main/res/layout/session_item.xml, app/src/main/res/layout/student_profile.xml, app/src/main/res/layout/student_quick_book_item.xml, app/src/main/res/layout/tutor_profile.xml
Created content for the following views:
- Student Profile
- Tutor Profile
Created the following new views:
- Session item view
- Quick book item view
=> Application scaffolding

app/src/main/AndroidManifest.xml, app/src/main/java/cs/dal/krush/LoginMainActivity.java, app/src/main/java/cs/dal/krush/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/login_main.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
-Created a main login page with option to select between student and tutor with radio buttons.
-Main screen now has login and sign up options.
=> Login pages

.idea/markdown-exported-files.xml, .idea/markdown-navigator/profiles_settings.xml, app/src/main/java/cs/dal/krush/StudentMainActivity.java, app/src/main/java/cs/dal/krush/TutorMainActivity.java, app/src/main/java/cs/dal/krush/studentFragments/StudentBookingFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentHomeFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentSessionsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorAvailabilityFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorHomeFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorSessionsFragment.java
I passed userID into all fragments to make future development easier for everyone.
=> add-user-id-to-fragments: added logged in userID to all fragments

.idea/misc.xml, app/src/main/java/cs/dal/krush/studentFragments/StudentBookingFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentHomeFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileEditFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentSessionsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorAvailabilityFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorHomeFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileEditFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorSessionsFragment.java
Fixed an issue where the USER_ID variables didn't merge properly with Connor's profile changes.
=> fix-master-1: Fixed merge conflicts with profile views.

.idea/misc.xml, app/src/main/java/cs/dal/krush/models/TutoringSession.java, app/src/main/java/cs/dal/krush/seeders/TutoringSessionSeeder.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorAvailabilityFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorCalendarFragment.java
Calendar fragment now syncs up with the tutor's availability for the month. Also updated seeders.
=> Issue#75 display tutor availability week

.idea/markdown-navigator.xml, .idea/markdown-navigator/profiles_settings.xml, .idea/misc.xml, app/src/main/java/cs/dal/krush/tutorFragments/TutorAvailabilityFragment.java, app/src/main/res/layout/tutor_availability.xml
=> Added custom font to Tutor Availability View

app/src/main/java/cs/dal/krush/StudentCursorAdapters/HomeUpcomingSessionsCursorAdapter.java, app/src/main/java/cs/dal/krush/models/TutoringSession.java
=> Added locations to the upcoming sessions list

app/src/main/java/cs/dal/krush/appFragments/SessionDetailsFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentBookingFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentHomeFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentTutorDetailsFragment.java, app/src/main/res/layout/session_details.xml, app/src/main/res/layout/student_tutor_details.xml
- Added onClick listeners for for both lists on home fragment and booking fragment
- When a list item is clicked the session_id or tutor_id is extracted and passed to new fragment
- session details fragment and tutor details fragment created with basic placeholder info
=> Student home and booking select list items: #74 and #73

app/src/main/java/cs/dal/krush/tutorFragments/TutorHomeFragment.java, app/src/main/res/layout/tutor_help.xml, app/src/main/res/layout/tutor_home.xml
**Completed**
- Created a dialog for help section
- Added button on tutor home view
- Created template for the dialog
**To do**
- Since the implementation for our core functionality isn't completed yet, I used place holder text for now. Once, we near the end of the project I will update the text.
Closes #58
=> Tutor help

app/src/main/AndroidManifest.xml, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileEditFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileEditFragment.java
- Updated the manifest with the permission requirements
- Added run time check _IF_ permission isn't already given
- Added the code in both student and tutor edit pages
- Tested on API 23 an 25
Closes #89
=> Camera Permission

app/src/main/java/cs/dal/krush/models/AvailableTime.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorAvailabilityFragment.java, app/src/main/res/layout/tutor_availability.xml
Correctly displays and parses dates to display in the listview. Added method to strip leading zeros and seconds from a time string. There is now validation when trying to submit an available timeslot without all required fields. Updated button design, now they're shorter.
=> Bug fixes, updated query and fetching method. Added validation.

app/src/main/java/cs/dal/krush/models/TutoringSession.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorHistoryDetailsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorHomeFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorSessionsDetailsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorSessionsFragment.java, app/src/main/res/drawable/button_cancel.xml, app/src/main/res/layout/tutor_home_upc_session_details.xml, app/src/main/res/layout/tutor_sessions_details.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
- Tutor Upcoming Sessions list item view
- Tutor Session History list item view
This closes #94 
The video displays all sessions in the `upcoming` sessions list view in the video for testing / display purposes only. I added the `future events only` part back to the query after making the video.
=> Setup tutor list item views

app/src/main/java/cs/dal/krush/helpers/DateFormatHelper.java, app/src/main/java/cs/dal/krush/models/AvailableTime.java, app/src/main/java/cs/dal/krush/models/CoursesTutors.java, app/src/main/java/cs/dal/krush/models/Tutor.java, app/src/main/java/cs/dal/krush/models/TutoringSession.java, app/src/main/java/cs/dal/krush/seeders/AvailableTimeSeeder.java, app/src/main/java/cs/dal/krush/seeders/DatabaseSeeder.java, app/src/main/java/cs/dal/krush/studentFragments/StudentPaymentFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileEditFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentTutorDetailsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileEditFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileFragment.java, app/src/main/res/layout/student_profile.xml, app/src/main/res/layout/student_profile_edit.xml, app/src/main/res/layout/student_tutor_details.xml, app/src/main/res/layout/tutor_profile.xml, app/src/main/res/layout/tutor_profile_edit.xml, app/src/main/res/values/strings.xml
-Designed booking view to closly match tutor profile view
-Displays a tutors rating, school, rate, location, courses, and availability
-Book now button takes you to the StudentPaymentFragment
-Passing any variables needed to create a new session through bundles into this view
-On a successful payment a new session is created and the user is redirected to the session details
-Added a DateFormatHelper for converting our dates into more readable strings
-Added various helper methods in some of the models for getting the data I needed for the booking view
-Added a seeder for available_times to test the booking view
=> Booking view

app/src/main/java/cs/dal/krush/RegistrationActivity.java, app/src/main/java/cs/dal/krush/models/DBHelper.java, app/src/main/java/cs/dal/krush/models/Tutor.java, app/src/main/java/cs/dal/krush/models/TutorRating.java, app/src/main/java/cs/dal/krush/models/TutoringSession.java, app/src/main/java/cs/dal/krush/seeders/DatabaseSeeder.java, app/src/main/java/cs/dal/krush/seeders/TutorRatingSeeder.java, app/src/main/java/cs/dal/krush/seeders/TutorSeeder.java, app/src/main/java/cs/dal/krush/studentFragments/StudentHistoryDetailsFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentSessionsFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentTutorDetailsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorHistoryDetailsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorHomeFragment.java, app/src/main/res/layout/student_sessions_details.xml, app/src/main/res/layout/student_tutor_details.xml
- Added rating functionality to session history page
- Can view tutor ratings on student and tutor fragments
- Created new page, fragment, and query for student history sessions
- Fixed old queries
=> Tutor ratings

README.md, app/build.gradle, app/src/debug/res/values/google_maps_api.xml, app/src/main/AndroidManifest.xml, app/src/main/java/cs/dal/krush/models/Location.java, app/src/main/java/cs/dal/krush/models/Tutor.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorAvailabilityFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorLocationFragment.java, app/src/main/res/layout/activity_tutor_maps.xml, app/src/main/res/layout/tutor_availability.xml, app/src/main/res/layout/tutor_location.xml, app/src/main/res/values/strings.xml, app/src/release/res/values/google_maps_api.xml
- Added Google Maps API key to the project
- Added project space requirements for Google Maps
- Updated project manifest
- Created TutorLocationFragment with Google Map fragment
- Fixed `getDataByLocation()`
- Added `updateTutorLocation()`
- Styled map marker with application primary colour
- Added reference
**DB**
**Marker**
**In action**
Closes #72
=> Tutor location

app/src/main/java/cs/dal/krush/adapters/CustomTutorDayTimeAdapter.java
Only missed instantiating the format helper.
=> Instantiated DateFormatHelper

app/src/main/java/cs/dal/krush/tutorFragments/TutorHistoryDetailsFragment.java
=> Fixed error message on tutor history details view

app/src/main/res/layout/tutor_availability.xml
=> Reordered the tutor availability fragment view

app/src/main/java/cs/dal/krush/RegistrationActivity.java, app/src/main/java/cs/dal/krush/helpers/ValidationHelper.java, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileEditFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileEditFragment.java
- Added a number check to the rate field
- Added email validation to the register view, student profile view, and tutor profile view.
This closes #135
=> bug-tutor-profile-rate: Fixed rate number validation bug

app/src/main/java/cs/dal/krush/RegistrationActivity.java, app/src/main/java/cs/dal/krush/StudentCursorAdapters/BookingTutorCursorAdapter.java, app/src/main/java/cs/dal/krush/StudentCursorAdapters/HomeQuickBookCursorAdapter.java, app/src/main/java/cs/dal/krush/StudentCursorAdapters/SessionCursorAdapter.java, app/src/main/java/cs/dal/krush/models/AvailableTime.java, app/src/main/java/cs/dal/krush/models/CoursesTutors.java, app/src/main/java/cs/dal/krush/models/Student.java, app/src/main/java/cs/dal/krush/models/Tutor.java, app/src/main/java/cs/dal/krush/studentFragments/StudentBookingDetailsFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentPaymentFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileEditFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentProfileFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentUpcSessionsDetailsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileEditFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorProfileFragment.java, app/src/main/res/drawable/button_change_picture.xml, app/src/main/res/drawable/button_main.xml, app/src/main/res/layout/student_home_upc_session_details.xml, app/src/main/res/layout/student_profile.xml, app/src/main/res/layout/student_profile_edit.xml, app/src/main/res/layout/student_tutor_details.xml, app/src/main/res/layout/tutor_profile.xml, app/src/main/res/layout/tutor_profile_edit.xml, app/src/main/res/values/colors.xml
Adding school type (university, highschool, etc) to all instances of school names
-Added database methods in Student and Tutor to return the school name and type given their id
-Modified student and tutor profile fragments to use new methods
-Modified student and tutor edit fragments to append the school type to the list of school names
-Modified registration activitiy to append school type to name
-Modified student booking view to display the tutors school name and type
Modified all student and tutor profile and edit views to be consistent with styling
-Added labels to all fields and applied app style
-Added password validation to show errors to user if incorrect information was entered
-Added check for null tutor rate and replace with text informing tutor to set rate or that a rate has …
=> Profile improvements

.idea/misc.xml, app/src/main/java/cs/dal/krush/studentFragments/StudentUpcSessionsDetailsFragment.java, app/src/main/res/layout/student_home_upc_session_details.xml
- Added play functionality to upcoming session details page
=> Play recordings

app/src/main/java/cs/dal/krush/RegistrationActivity.java, app/src/main/java/cs/dal/krush/models/DBHelper.java, app/src/main/java/cs/dal/krush/models/Tutor.java, app/src/main/java/cs/dal/krush/seeders/TutorSeeder.java, app/src/main/java/cs/dal/krush/studentFragments/StudentBookingDetailsFragment.java, app/src/main/java/cs/dal/krush/studentFragments/StudentHistoryDetailsFragment.java, app/src/main/java/cs/dal/krush/tutorFragments/TutorHomeFragment.java, app/src/main/res/layout/student_booking_listentry.xml, app/src/main/res/layout/student_payment.xml, app/src/main/res/layout/student_tutor_details.xml, app/src/main/res/layout/tutor_home.xml
- Added rating count to booking views and tutor home
=> Added rating count

app/src/main/java/cs/dal/krush/studentFragments/StudentUpcSessionsDetailsFragment.java
- Fixed cancel issue
- Reinitialized db connection
=> Cancel fix

app/src/main/java/cs/dal/krush/studentFragments/StudentUpcSessionsDetailsFragment.java, app/src/main/res/layout/student_home_upc_session_details.xml
- Removed play button and MediaPlayer
- Will play audio recordings from device not app
=> Removed play recording button
